const daysData: Day[] = [
   {
      date: '2024-06-01',
      day: 'сб',
      isDayOff: true,
   },
   {
      date: '2024-06-02',
      day: 'вс',
      isDayOff: true,
   },
   {
      date: '2024-06-03',
      day: 'пн',
      isDayOff: false,
   },
   {
      date: '2024-06-04',
      day: 'вт',
      isDayOff: false,
   },
   {
      date: '2024-06-05',
      day: 'ср',
      isDayOff: false,
   },
   {
      date: '2024-06-06',
      day: 'чт',
      isDayOff: false,
   },
   {
      date: '2024-06-07',
      day: 'пт',
      isDayOff: false,
   },
   {
      date: '2024-06-08',
      day: 'сб',
      isDayOff: true,
   },
   {
      date: '2024-06-09',
      day: 'вс',
      isDayOff: true,
   },
   {
      date: '2024-06-10',
      day: 'пн',
      isDayOff: false,
   },
   {
      date: '2024-06-11',
      day: 'вт',
      isDayOff: false,
   },
   {
      date: '2024-06-12',
      day: 'ср',
      isDayOff: false,
   },
   {
      date: '2024-06-13',
      day: 'чт',
      isDayOff: false,
   },
   {
      date: '2024-06-14',
      day: 'пт',
      isDayOff: false,
   },
   {
      date: '2024-06-15',
      day: 'сб',
      isDayOff: true,
   },
   {
      date: '2024-06-16',
      day: 'вс',
      isDayOff: true,
   },
   {
      date: '2024-06-17',
      day: 'пн',
      isDayOff: false,
   },
   {
      date: '2024-06-18',
      day: 'вт',
      isDayOff: false,
   },
   {
      date: '2024-06-19',
      day: 'ср',
      isDayOff: false,
   },
   {
      date: '2024-06-20',
      day: 'чт',
      isDayOff: false,
   },
   {
      date: '2024-06-21',
      day: 'пт',
      isDayOff: false,
   },
   {
      date: '2024-06-22',
      day: 'сб',
      isDayOff: true,
   },
   {
      date: '2024-06-23',
      day: 'вс',
      isDayOff: true,
   },
   {
      date: '2024-06-24',
      day: 'пн',
      isDayOff: false,
   },
   {
      date: '2024-06-25',
      day: 'вт',
      isDayOff: false,
   },
   {
      date: '2024-06-26',
      day: 'ср',
      isDayOff: false,
   },
   {
      date: '2024-06-27',
      day: 'чт',
      isDayOff: false,
   },
   {
      date: '2024-06-28',
      day: 'пт',
      isDayOff: false,
   },
   {
      date: '2024-06-29',
      day: 'сб',
      isDayOff: false,
   },
   {
      date: '2024-06-30',
      day: 'вс',
      isDayOff: false,
   },
];

const eventsData: DayEvent[] = [
   {
      id: 2,
      title: 'День рождения друга',
      start: '14:00',
      end: '18:00',
      color: 'blue',
      isCompleted: false,
      date: '2024-06-01',
      description: 'Не забыть купить подарок',
   },
   {
      id: 2,
      title: 'Afterparty 🎉',
      start: '19:00',
      end: '22:00',
      color: 'blue',
      isCompleted: false,
      date: '2024-06-01',
   },
   {
      id: 3,
      title: 'Едем на рыбалку с Игорем',
      start: '06:00',
      end: '12:00',
      color: 'green',
      isCompleted: true,
      date: '2024-06-03',
   },
   {
      id: 4,
      title: 'Заплатить за свет',
      start: '09:00',
      end: '09:30',
      color: 'yellow',
      isCompleted: false,
      date: '2024-06-05',
      description: 'Надо успеть до 10 числа',
   },
   {
      id: 5,
      title: 'Срочное совещание',
      start: '11:00',
      end: '12:30',
      color: 'pink',
      isCompleted: false,
      date: '2024-06-07',
   },
   {
      id: 6,
      title: 'Купить новый ноутбук',
      start: '16:00',
      end: '17:00',
      color: 'blue',
      isCompleted: true,
      date: '2024-06-10',
   },
   {
      id: 7,
      title: 'Поездка в парк с семьей',
      start: '10:00',
      end: '13:00',
      color: 'green',
      isCompleted: false,
      date: '2024-06-12',
      description: 'Пикник и прогулка',
   },
   {
      id: 8,
      title: 'Встреча с клиентом',
      start: '15:00',
      end: '16:00',
      color: 'yellow',
      isCompleted: false,
      date: '2024-06-14',
   },
   {
      id: 9,
      title: 'Семинар по веб-разработке',
      start: '09:00',
      end: '11:00',
      color: 'pink',
      isCompleted: false,
      date: '2024-06-15',
   },
   {
      id: 18,
      title: 'Окучивание веб-грядок',
      start: '11:00',
      end: '14:00',
      color: 'blue',
      isCompleted: false,
      date: '2024-06-15',
   },
   {
      id: 19,
      title: 'Пожинание веб-урожая',
      start: '15:00',
      end: '21:00',
      color: 'blue',
      isCompleted: false,
      date: '2024-06-15',
      description: 'Обязательно собрать кибер-огурцы!',
   },
   {
      id: 10,
      title: 'Купить продукты',
      start: '18:00',
      end: '19:00',
      color: 'blue',
      isCompleted: false,
      date: '2024-06-18',
   },
   {
      id: 11,
      title: 'Отпуск начинается!',
      start: '00:00',
      end: '23:59',
      color: 'green',
      isCompleted: false,
      date: '2024-06-20',
      description: 'Долгожданный отпуск',
   },
   {
      id: 12,
      title: 'Ужин с родителями',
      start: '19:00',
      end: '21:00',
      color: 'pink',
      isCompleted: false,
      date: '2024-06-21',
   },
   {
      id: 13,
      title: 'Поход в кино',
      start: '17:00',
      end: '19:00',
      color: 'yellow',
      isCompleted: true,
      date: '2024-06-23',
   },
   {
      id: 14,
      title: 'Забрать посылку с почты',
      start: '10:00',
      end: '10:30',
      color: 'pink',
      isCompleted: false,
      date: '2024-06-24',
   },
   {
      id: 15,
      title: 'Спортивные соревнования',
      start: '08:00',
      end: '12:00',
      color: 'blue',
      isCompleted: true,
      date: '2024-06-26',
   },
   {
      id: 16,
      title: 'Йога на пляже',
      start: '07:00',
      end: '08:00',
      color: 'green',
      isCompleted: false,
      date: '2024-06-29',
   },
   {
      id: 17,
      title: 'Праздник на работе',
      start: '13:00',
      end: '15:00',
      color: 'pink',
      isCompleted: true,
      date: '2024-06-30',
      description: 'Празднование достижения квартальных целей',
   },
];

export { daysData, eventsData };
